# Generated by Django 6.1 on 2026-08-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='fullname',
            new_name='Nombre',
        ),
    ]
