# Generated by Django 6.1 on 2026-08-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fullname_programmer_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='sistema_especializado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
